# This specifies the number of layers and number of hidden neurons in each layer.
layer_specs: [58, 128, 256, 10]  

# Type of non-linear activation function to be used for the layers.
activation: "ReLU"

# The learning rate to be used for training.
learning_rate: 0.2

# Number of training samples per batch to be passed to network
batch_size: 16

# Number of epochs to train the model
epochs: 100

# Flag to enable early stopping
early_stop: True

# History for early stopping. Wait for this many epochs to check validation loss / accuracy.
early_stop_epoch: 5

# Regularization constant
L2_penalty: 0.05

# Use momentum for training
momentum: True

# Value for the parameter 'gamma' in momentum
momentum_gamma: 0.3

#Weight Type
weight_type: "random"